[book]
title = "SBS Pāli-English Recitations"
authors = ["SBS Saṅgha"]
language = "en"
multilingual = false
src = "manuscript/markdown"

[build]
build-dir = "book"
create-missing = true

[output.html]
additional-css = ["assets/stylesheets/output-html.css"]
curly-quotes = true

[output.epub]
additional-css = ["assets/stylesheets/output-epub.css"]
use-default-css = false
cover-image = "front-cover-compressed.jpg"
additional-resources = ["assets/fonts/LibertinusSerif-Regular.otf", "assets/fonts/LibertinusSerif-Italic.otf", "assets/fonts/LibertinusSerif-Bold.otf", "assets/fonts/LibertinusSerif-Regular.otf"]
