---

name: Build documents
'on':
  push:
    branches:
      - main
env:
  TEST_UPLOADING: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: bergentroll/pali-english-recitations-builder:latest
    defaults:
      if: env.TEST_UPLOADING != 'true'
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3
        if: true
      - name: Create MOC files
        run: |
          mkdir build/
          date | tee build/file.pdf build/file.epub build/file.azw3
        if: env.TEST_UPLOADING == 'true'
      - name: Build PDF
        run: make pdf2x
      - name: Build EPUB
        run: make epub
      - name: Build AZW3
        run: make azw3
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto
          files: |
            build/*.azw3
            build/*.epub
            build/*.pdf
          fail_on_unmatched_files: true
        if: true
