---

name: Build documents
'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: bergentroll/pali-english-recitations-builder:latest
    permissions:
      contents: write
    steps:
      - name: install curl
        run: apt update && apt-get install curl -y
      - uses: bergentroll/sasanarakkha-build-ebooks-action@v1
        with: {}
